#!/bin/bash
g++ upload.cpp -std=c++14 -static -o run
systemd-run -p MemoryMax=125M -p MemorySwapMax=0 -p CPUQuota=100% -p TimeoutStopSec=0.999999 \
    --user -t --wait --collect \
    bash -c "./run <data.in >data.out 2>run.log"
echo Exit Code: $?
diff -w data.out data.ans
