#!/bin/bash
if [ ! -e "upload.cpp" ]; then
    echo -e "\033[31mSource File not Found!\033[0m"
    exit 1
fi

g++ upload.cpp -o2 -std=c++14 -Wl,--stack=14104857600 -g -o run

if [ $? -ne 0 ]; then
    echo -e "\033[31mBuild Error!\033[0m"
    exit 1
fi


if [ ! -e "data.in" ]; then
    echo -e "\033[31mInput File not Found!\033[0m"
    exit 1
fi

time cat data.in | ./run 1>data.out 2>run.log

if [ $? -ne 0 ]; then
    echo -e "\033[35mRuntime Error!\033[0m"
    exit 1
fi

rm run.log

if [ -e "data.ans" ]; then
    echo -e "\033[37mAnswer File not Found!\033[0m"
    exit 0
fi

diff data.out data.ans -w 1>/dev/null 2>/dev/null

if [ $? -ne 0 ]; then
    echo -e "\033[31mWrong Answer!\033[0m"
    exit 1
fi


rm data.out
echo -e "\033[32mAnswer Correct!\033[0m"