#!/bin/bash
echo "$(pwd)/run 0<$(pwd)/data.in 1>$(pwd)/data.out" > script
g++ upload.cpp -std=c++14 -static -o run
echo Complete: $?
echo
systemd-run -p MemoryMax=256M -p MemorySwapMax=0 -p CPUQuota=100% -p TimeoutStopSec=1.2 \
    --user -t --wait --collect \
    bash $(pwd)/script
rm script
echo
diff -w data.out data.ans 
echo Difference: $?