#!/bin/bash
rm build.log
g++ struct.cpp -O2 -std=c++14 -g -o run 2>build.log
if [ $? -ne 0 ];
then
    echo -e "\033[31mBuild Error!\033[0m"
    echo
    exit 1
fi
time ./run 2>run.log
if [ $? -ne 0 ];
then
    echo -e "\033[35mRuntime Error!\033[0m"
    echo
    exit 1
fi
diff struct.out struct.ans -w 1>/dev/null 2>/dev/null
if [ $? -ne 0 ];
then
    echo -e "\033[31mWrong Answer!\033[0m"
    echo
    exit 1
fi
rm struct.out
rm run.log
echo -e "\033[32mAnswer Correct!\033[0m"
echo
