#!/bin/bash
g++ upload.cpp -std=c++14 -static -o run

echo "#!/bin/bash" > runner
echo "$(pwd)/run 0<$(pwd)/data.in 1>$(pwd)/data.out 2>$(pwd)/data.log" >> runner
systemd-run -p MemoryMax=125M -p MemorySwapMax=0 -p CPUQuota=100% -p TimeoutStopSec=0.999999 \
    --user -t --wait --collect \
    bash $(pwd)/runner
echo Exit Code: $?
rm run
rm runner

echo
diff -w data.out data.ans 
echo Difference: $?